// <auto-generated>

using System;
using System.Collections.Generic;

#nullable disable

namespace WinReactApp.ManageUsers.Models
{
    public partial class AddressType
    {
        public long AddressTypeId { get; set; }
        public string AddressType1 { get; set; }
        public bool? IsActive { get; set; }
    }
}
